### ISSUE TITLE
[FEATURE] Account Login

### ISSUE THREAD

**Issue by patrickmuigaih** [BuildForSDG/team-159#4]
**Story Title:**
As a User, I should be able to login to M-Uwezo

**Narrative:**
As a User, I should be able to fill the login form with the required fields, so that I'm able to login

**Acceptance criteria:**
**scenario 1:**
GIVEN I want to login to M-Uwezo as a user
WHEN User navigates to the user/login.html route
THEN The User should be able to fill a form with their login details to login to the application

**scenario 2:**
Given I want to login to M-Uwezo as a user,
And I have the correct API endpoint,
When I send a POST request method with

email
password
Then I should get response 201 with token and name of newly user

**branch names**
ft-register-user-163630766
ft-v2-register-user-16363076

**Comment by ghost** [comment]
Registered Users can now Log in to M-Uwezo
