### ISSUE TITLE
[FEATURE] Account Registration

### ISSUE THREAD

**Issue by Muringo** [BuildForSDG/team-159#6]
**Story Title:**
As a Customer, I should be able to register to M-Uwezo

**Narrative:**
As a Customer, I should be able to fill the registration form with the required fields, so that I'm able to register

**Acceptance criteria:
scenario 1:**
GIVEN I want to register to M-Uwezo as a customer
WHEN Customer navigates to the customer/register.html route
THEN The Customer should be able to fill a form with their registration details to register

**scenario 2:**
Given I want to register to M-Uwezo as a Customer,
And I have the correct API endpoint,
When I send a POST request method with

business number
email
full name
national id
phone number
Then I should get response 201 with token and name of newly Customer

**branch names**
ft-register-user-163630766
ft-v2-register-user-16363076

**Comment by ghost** [comment]
User can now register to m-uwezo
